# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02f72734522778f275e5616a41d76383aeb61d7904c10e0539f93d1bc3285d584a7dbdcad288107637f3f84f0254b4322ae7915865b4fe7d885f5aae1913d6c

test:
  secret_key_base: 9f1bf3c6fc4f829658acec4e4bcfd9aa378c93f9479b91159190f4a4191f641064b90941d887a849fa3709eb440353901d2bc514b6bb42be78ede047a93a007d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
